export const LABEL_CHALLENGE = 'klodd.tjcsec.club/challenge'
export const LABEL_TEAM = 'klodd.tjcsec.club/team'
export const LABEL_POD = 'klodd.tjcsec.club/pod'
export const LABEL_INSTANCE = 'klodd.tjcsec.club/instance'
export const LABEL_EGRESS = 'klodd.tjcsec.club/egress'
export const LABEL_MANAGED_BY = 'app.kubernetes.io/managed-by'
export const LABEL_MANAGED_BY_VALUE = 'klodd'
export const ANNOTATION_TTL = 'klodd.tjcsec.club/ttl'
